// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MyCompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productFeature = ProductFeatureEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, category);
            ProductFeatureEntityType.CreateForeignKey1(productFeature, product);

            CategoryEntityType.CreateAnnotations(category);
            ProductEntityType.CreateAnnotations(product);
            ProductFeatureEntityType.CreateAnnotations(productFeature);

            AddAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
